### PR TITLE
Tutorial/rik sample

### PR DESCRIPTION
**Pull request by shuufei**
テストPR

### CODE REVIEW

**Comment by shuufei** [comment]
@reynard93 

> https://github.com/shuufei/digimon-card-mobile-app の ユーザ名 と パスワード ください

すみません、sign in情報は公開していません

**Comment by reynard93** [comment]
> @reynard93
> 
> > [](https://github.com/shuufei/digimon-card-mobile-app)Please enter your username and password for https://github.com/shuufei/digimon-card-mobile-app
> 
> I'm sorry, sign in information is not disclosed

can you help me create an account? would like to look around the app. thank you so much

**Comment by shuufei** [comment]
We are sorry, but we cannot create an account for you.
This project is being developed so that only @shuufei  and @riki-hanashiro  can play.
The source code is public, but we do not plan to release the application itself.

> would like to look around the app

What is the purpose of this?
Depending on the purpose, there may be something we can do.

**Comment by reynard93** [comment]
> We are sorry, but we cannot create an account for you. This project is being developed so that only @shuufei and @riki-hanashiro can play. The source code is public, but we do not plan to release the application itself.
> 
> > would like to look around the app
> 
> What is the purpose of this? Depending on the purpose, there may be something we can do.

thank you for replying, i am just looking at the code in order to help for school assignment own project. Would be helpful for me to just look around, if not just having screenshots would help me too.

**Comment by shuufei** [comment]
I will send you a screenshot later.
Please wait a moment.

**Comment by reynard93** [comment]
checked!! ty 👍 😃

**Pull request closed without merging**
